//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cater
    {
        public int CaterID { get; set; }
        public int ProdID { get; set; }
        public int CatID { get; set; }
        public System.DateTime CDate { get; set; }
        public decimal WCat { get; set; }
        public decimal Price { get; set; }
    
        public virtual Caterer Caterer { get; set; }
        public virtual Product Product { get; set; }
    }
}
