//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingred
    {
        public int IngredID { get; set; }
        public int FoodID { get; set; }
        public int ProdID { get; set; }
        public string Name { get; set; }
        public decimal WProd { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Product Product { get; set; }
    }
}
