//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portion
    {
        public int PortionID { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public Nullable<decimal> CountPortion { get; set; }
        public Nullable<int> FoodID { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
